language: python

sudo: false

cache: pip

python:
  - 2.7
  - 3.6

install:
  - pip install pip setuptools wheel --upgrade
  - pip install .\[test\]

script:
  - pytest --cov rio_ds_mask --cov-report term-missing

after_success:
  - coveralls
