language: python

sudo: false

cache: pip

python:
  - 2.7
  - 3.6

install:
  - pip install pip setuptools wheel --upgrade
  # More recent Rasterio releases include Linux wheels containing a
  # minimal version of GDAL, which means GDAL does not need to be
  # installed directly.
  - pip install "rasterio>=1.0a12"
  - pip install .\[test\]

script:
  - pytest --cov rio_ds_mask --cov-report term-missing

after_success:
  - coveralls
